query Articles ( $slug : String){
  articles( where : { slug :$slug } ) {
    title
    excerpt
    content
    homepage
    random_image
    tags
    image { 
        name 
        url
    }
    gallery {
        name
        url
    }
    image_title
    updated_at
    SEO {
        description
        title
    }
    categories {
        name
        slug
    }
    parent {
      slug
      title
    }
    template {
      id
      name
      class
      fields {
        name
        class
        shortcode 
        textbox
        widget {
            id
        }
        menu {
          id
        }
      }
      fields_col_2 {
        name
        class
        shortcode
        textbox
        widget {
            id
        }
        menu {
          id
        }
      }
      fields_col_3 {
        name
        class
        shortcode
        textbox
        widget {
            id
        }
        menu {
          id
        }
      }
    }
  } 
}